version: "3"

services:
  api:
    build: ./api
    container_name: api
    restart: always
    expose:
      - 5000
    depends_on:
      - mysql
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./mysql/.env
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d/
    logging:
        options:
            max-size: 10m
            max-file: "3"