version: "3"

services:
  mysql:
    container_name: mysql
    build: ./mysql
    ports:
      - "3306:3306"
    env_file:
      - ./mysql/.env
    volumes:
      - ./mysql/data:/var/lib/mysql
    logging:
        options:
            max-size: 10m
            max-file: "3"