version: "3"

services:
  mysql:
    container_name: mysql
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
    logging:
        options:
            max-size: 10m
            max-file: "3"